language: python
python:
  - 2.7
  - 3.4

env:
  - DJANGO="django<1.7"
  - DJANGO="django<1.8"
  - DJANGO="django<1.9"
  - DJANGO="django==1.9b1"

install:
  - pip install -q $DJANGO
  - python setup.py -q install

script:
  - ./manage.py test --settings=admin_sort.tests.settings
